default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [ --py36-plus ]

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
        - id: black
          args: ['-l 88', '--diff']
          stages: [commit, push]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
        - id: detect-private-key
        - id: trailing-whitespace
          exclude: assets/
          types: [python]
        - id: check-yaml
        - id: check-json
        - id: check-toml
        - id: check-added-large-files
          args: ['--maxkb=1024']
        - id: check-docstring-first
        - id: end-of-file-fixer
          types: [python]
        - id: name-tests-test

