name: icecube_env
channels:  
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - rasterio
  - h5py
  - xmltodict
  - tqdm
  - pip
  - scikit-image
  - invoke
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - pip:
    - opencv-python
    - black
    - shapely
    - pandas
    - pytest
    - -e .
