site_name: ICEcube Documentation
site_description: Manipulate coregistered ICEYE SAR Image Stacks in Python

# Repository
repo_name: iceye-ltd/icecube
repo_url: https://github.com/iceye-ltd/icecube
edit_uri: edit/main/docs/
site_url: https://iceye-ltd.github.io/icecube/

theme:
  palette:
    primary: black
    accent: green
  name: material
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Installation: installation.md
  - ICEcube Examples:
    - GRD Datacube Input / Output : examples/Ex1_GRD_input_output.ipynb
    - SLC Datacube Input / Output : examples/Ex2_SLC_input_output.ipynb
    - Labels Datacube : examples/Ex3_Labels.ipynb
    - Datacube : examples/Ex4_Datacube.ipynb
    - ML integration: examples/Ex5_Datacube_ML.ipynb

  - Implementation Details:
    - Datacube: datacube/Datacube.md

  - Contributing: contribute.md

markdown_extensions:
  - admonition

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
      watch:
        - icecube/
