name: pre-commit

on:
  pull_request:
  push:
    branches:
     - main
     - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  pytest:
    runs-on: ubuntu-latest
    steps:
    # no need exept if we decide to depend on the iceye_io
    #  - uses: webfactory/ssh-agent@v0.5.1
    #    with:
    #      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install invoke
          inv setup
          inv test
