name: pre-commit

on:
  pull_request:
  push:
    branches:
     - main
     - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          pip install invoke
          inv setup
          inv test
